add_executable(test_integrator test_integrator.cpp)
add_executable(test_einstein_ring test_einstein_ring.cpp)
add_executable(test_rotating_boson_star_geodesic test_rotating_boson_star_geodesic.cpp)
add_executable(test_boson_star_geodesic test_boson_star_geodesic.cpp)
add_executable(test_boson_star_interpolators test_boson_star_interpolators.cpp)

target_include_directories(test_integrator PUBLIC ${CMAKE_SOURCE_DIR}/FOORT/src)
target_include_directories(test_einstein_ring PUBLIC ${CMAKE_SOURCE_DIR}/FOORT/src)
target_include_directories(test_rotating_boson_star_geodesic PUBLIC ${CMAKE_SOURCE_DIR}/FOORT/src)
target_include_directories(test_boson_star_geodesic PUBLIC ${CMAKE_SOURCE_DIR}/FOORT/src)
target_include_directories(test_boson_star_interpolators PUBLIC ${CMAKE_SOURCE_DIR}/FOORT/src)

target_link_libraries(test_integrator PUBLIC config_lib metric_lib input_output_lib GTest::gtest_main)
target_link_libraries(test_einstein_ring PUBLIC config_lib metric_lib input_output_lib GTest::gtest_main)
target_link_libraries(test_rotating_boson_star_geodesic PUBLIC config_lib metric_lib input_output_lib GTest::gtest_main)
target_link_libraries(test_boson_star_geodesic PUBLIC config_lib metric_lib input_output_lib GTest::gtest_main)
target_link_libraries(test_boson_star_interpolators PUBLIC config_lib metric_lib input_output_lib GTest::gtest_main)

include(GoogleTest)
gtest_discover_tests(test_integrator)
gtest_discover_tests(test_einstein_ring)
gtest_discover_tests(test_rotating_boson_star_geodesic)
gtest_discover_tests(test_boson_star_geodesic)
gtest_discover_tests(test_boson_star_interpolators)
